export interface Quote {
  topic: string;
  text: string;
}

export const dailyQuotes: Quote[] = [
  // Chủ đề 1: Kỷ luật & Sức mạnh của Thói quen (25 quotes)
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật là cây cầu nối giữa mục tiêu và thành tựu.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Giá của kỷ luật luôn rẻ hơn giá của sự hối tiếc.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Chúng ta là những gì chúng ta làm đi làm lại. Sự xuất sắc không phải là một hành động, mà là một thói quen.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật tự giác bắt đầu bằng việc chiến thắng chiếc giường của bạn.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Người có kỷ luật là người tự do.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Động lực giúp bạn bắt đầu. Thói quen giúp bạn tiếp tục.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Bạn không quyết định tương lai của mình. Bạn quyết định thói quen của mình, và thói quen quyết định tương lai của bạn.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Gieo thói quen nhỏ, gặt tương lai lớn.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật không phải là hình phạt. Đó là sự lựa chọn giữa điều bạn muốn ngay bây giờ và điều bạn muốn nhất.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật là tình yêu thương bản thân ở mức độ cao nhất.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Thói quen tốt là nền tảng của mọi thành công.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Đừng chờ có hứng. Hãy tạo ra kỷ luật.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Sự khác biệt giữa người thành công và người thất bại nằm ở thói quen hàng ngày của họ.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật là làm điều bạn ghét làm, nhưng làm nó như thể bạn yêu thích nó. (Mike Tyson)' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Hôm nay, hãy chọn kỷ luật. Phiên bản tương lai của bạn sẽ cảm ơn bạn vì điều đó.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật không phải là giới hạn, nó là con đường dẫn đến tự do.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Chiến thắng bản thân là chiến thắng hiển hách nhất.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Một thói quen nhỏ được duy trì 99 ngày sẽ mạnh hơn một nỗ lực lớn chỉ trong 1 ngày.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật là vũ khí bí mật của những người phi thường.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Đừng để cảm xúc điều khiển bạn. Hãy để thói quen dẫn dắt bạn.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Thói quen buổi sáng mạnh mẽ tạo nên một ngày phi thường.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật là khả năng trì hoãn sự hài lòng tức thời để đổi lấy phần thưởng lớn hơn sau này.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Bạn sẽ không bao giờ hối tiếc vì đã sống một ngày có kỷ luật.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Hãy biến kỷ luật thành đồng minh, không phải kẻ thù của bạn.' },
  { topic: 'Kỷ luật & Sức mạnh của Thói quen', text: 'Kỷ luật hôm nay là sự tự do của ngày mai.' },

  // Chủ đề 2: Dậy sớm & Khởi đầu Ngày mới (15 quotes)
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: '4:45 AM. Trong khi người khác còn đang mơ, bạn đang biến giấc mơ thành hiện thực.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Chinh phục buổi sáng là chinh phục cả ngày.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Mặt trời còn chưa dậy, nhưng nhà vô địch trong bạn đã dậy.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Cách bạn bắt đầu ngày mới sẽ quyết định cách bạn sống cuộc đời mình.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Dậy sớm là khoản đầu tư vào phiên bản tốt hơn của chính bạn.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Đừng bắt đầu ngày mới bằng việc nhấn nút "hoãn". Hãy bắt đầu bằng một chiến thắng.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Buổi sáng là thời điểm vàng để rèn luyện tâm trí và cơ thể.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Tiếng chuông báo thức không phải là kẻ thù. Nó là lời kêu gọi hành động.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Người dậy sớm sở hữu một phần của ngày mà không ai khác có được.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Chào buổi sáng! Chiến thắng đầu tiên trong ngày đã thuộc về bạn.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Hãy thức dậy với sự quyết tâm. Hãy đi ngủ với sự hài lòng.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Mỗi buổi sáng là một trang giấy trắng. Hãy viết nên một câu chuyện tuyệt vời.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Buổi sáng sớm có vàng. (Benjamin Franklin)' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Dậy sớm không chỉ là một thói quen, đó là một lợi thế.' },
  { topic: 'Dậy sớm & Khởi đầu Ngày mới', text: 'Ngày mới, con người mới, tư duy mới. Bắt đầu thôi!' },

  // Chủ đề 3: Sự Kiên trì & Không bỏ cuộc (25 quotes)
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Thử thách 99 ngày không phải là một cuộc đua nước rút, đó là một cuộc đua marathon.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Đừng sợ đi chậm, chỉ sợ đứng yên.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Nỗi đau của kỷ luật chỉ là tạm thời. Nỗi đau của sự hối tiếc là mãi mãi.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Ngày hôm nay có thể khó khăn, nhưng bỏ cuộc sẽ không làm ngày mai dễ dàng hơn.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Ngã bảy lần, đứng dậy tám lần.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Bí mật của việc đi tới cùng là... chỉ cần không dừng lại.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Thành công là tổng hòa của những nỗ lực nhỏ lặp đi lặp lại mỗi ngày.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Khi bạn cảm thấy muốn bỏ cuộc, hãy nhớ lý do bạn bắt đầu.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: '99 ngày là một hành trình. Đừng vấp ngã ở ngày thứ 98.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Người chiến thắng là người không bao giờ bỏ cuộc.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Hãy kiên trì. Ngay cả một giọt nước cũng có thể làm mòn đá.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Khó khăn không tồn tại để đánh gục bạn, chúng tồn tại để làm bạn mạnh mẽ hơn.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Đừng dừng lại khi bạn mệt. Chỉ dừng lại khi bạn đã xong.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Sự khác biệt duy nhất giữa thành công và thất bại là khả năng chịu đựng.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Hành trình ngàn dặm bắt đầu từ một bước chân. (Lão Tử)' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Bạn mạnh mẽ hơn bạn nghĩ. Đừng từ bỏ.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Hãy tự hào về việc bạn đã đi được bao xa. Hãy tin tưởng vào việc bạn có thể đi xa hơn nữa.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Hôm nay là ngày 1, hoặc là 1 ngày nào đó. Bạn chọn đi.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Sự kiên định quan trọng hơn cường độ.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Cứ tiếp tục. Mọi thứ sẽ có ý nghĩa vào cuối hành trình.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Đừng để ngày hôm qua chiếm quá nhiều thời gian của ngày hôm nay.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Thành công không đến sau một đêm. Nó đến từ 99 buổi sáng như thế này.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Mọi nhà vô địch đều từng là một người không bỏ cuộc.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Thất bại duy nhất là khi bạn dừng cố gắng.' },
  { topic: 'Sự Kiên trì & Không bỏ cuộc', text: 'Bạn đã đi xa đến thế này, không phải để dừng lại ở đây.' },

  // Chủ đề 4: Phát triển Bản thân & Sự Thay đổi (15 quotes)
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Hôm nay, hãy tốt hơn 1% so với hôm qua.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Hành trình 99 ngày này là để xây dựng một con người mới từ gốc rễ.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Thay đổi không đến từ sự thoải mái. Nó đến từ thử thách.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Phiên bản tốt nhất của bạn đang chờ đợi ở phía bên kia của sự kỷ luật.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Đầu tư vào bản thân là khoản đầu tư mang lại lợi nhuận cao nhất.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Bạn của 99 ngày sau sẽ cảm ơn bạn của ngày hôm nay.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Đừng cố gắng để trở nên hoàn hảo. Hãy cố gắng để trở nên tốt hơn.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Bạn không thể thay đổi quá khứ, nhưng bạn có thể thay đổi tương lai bằng hành động của hôm nay.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Trở thành phiên bản mạnh mẽ hơn của chính mình. Đó là mục tiêu.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Vùng an toàn là một nơi đẹp đẽ, nhưng không có gì phát triển ở đó.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Cuộc sống bắt đầu ở nơi kết thúc vùng an toàn của bạn.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Sự thay đổi là đau đớn, nhưng không có gì đau đớn bằng việc mắc kẹt ở nơi bạn không thuộc về.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Bạn được sinh ra để làm nhiều điều hơn là chỉ tồn tại.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Đừng nâng cấp điện thoại của bạn. Hãy nâng cấp bản thân bạn.' },
  { topic: 'Phát triển Bản thân & Sự Thay đổi', text: 'Thay đổi bản thân, thay đổi cuộc đời.' },

  // Chủ đề 5: Sức khỏe & Thể chất (15 quotes)
  { topic: 'Sức khỏe & Thể chất', text: 'Hãy chăm sóc cơ thể của bạn. Đó là nơi duy nhất bạn phải sống.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Vận động là liều thuốc mạnh nhất.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Mồ hôi là giọt nước mắt của mỡ thừa.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Cơ thể bạn có thể làm được hầu hết mọi thứ. Chính tâm trí của bạn là thứ bạn cần thuyết phục.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Đừng tập luyện vì bạn ghét cơ thể mình. Hãy tập luyện vì bạn yêu nó.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Mỗi buổi tập là một món quà bạn tự tặng cho mình.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Năng lượng và sự kiên trì chinh phục mọi thứ.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Cơ thể khỏe mạnh là ngôi nhà cho một tâm trí khỏe mạnh.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Đừng tìm thời gian để tập. Hãy tạo ra thời gian để tập.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Bạn chỉ cách một buổi tập để có tâm trạng tốt hơn.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Sức khỏe là tài sản lớn nhất.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Giới hạn duy nhất của bạn là chính bạn.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Hôm nay đau một chút, ngày mai mạnh hơn một chút.' },
  { topic: 'Sức khỏe & Thể chất', text: 'Hãy làm cho cơ thể bạn mỉm cười.' },
  { topic: 'Sức khỏe & Thể chất', text: '30 phút tập luyện chỉ chiếm 2% thời gian trong ngày của bạn. Đừng viện cớ.' },

  // Chủ đề 6: Tư duy Tích cực & Lòng Biết ơn (15 quotes)
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Bắt đầu ngày mới với một trái tim biết ơn.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Lòng biết ơn biến những gì chúng ta có thành đủ.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Hãy tìm 3 điều bạn biết ơn sáng nay. Đó là nhiên liệu cho cả ngày.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Tư duy của bạn quyết định trải nghiệm của bạn. Hãy chọn sự tích cực.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Thay đổi cách bạn nhìn mọi thứ, và mọi thứ bạn nhìn sẽ thay đổi.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Bạn là những gì bạn nghĩ. Hãy nghĩ đến sự mạnh mẽ, kỷ luật và biết ơn.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Một tư duy tích cực mang lại kết quả tích cực.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Lòng biết ơn là vitamin cho tâm hồn.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Tập trung vào điều tốt đẹp, và điều tốt đẹp sẽ đến.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Mỗi ngày có thể không tốt, nhưng luôn có điều gì đó tốt trong mỗi ngày.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Hãy là năng lượng tích cực mà bạn muốn thu hút.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Đừng để những điều nhỏ nhặt phá hỏng hạnh phúc của bạn.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Kiểm soát tâm trí của bạn, hoặc nó sẽ kiểm soát bạn.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Lòng biết ơn là thói quen của những người thành công.' },
  { topic: 'Tư duy Tích cực & Lòng Biết ơn', text: 'Mỉm cười. Bạn đã chọn thức dậy và trở nên tốt hơn.' },

  // Chủ đề 7: Sức mạnh Cộng đồng & Đồng đội (10 quotes)
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Một mình bạn đi nhanh. Cùng nhau chúng ta đi xa.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Hôm nay, hãy là lý do khiến một đồng đội của bạn không bỏ cuộc.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Chúng ta cùng nhau dậy sớm. Chúng ta cùng nhau chiến thắng.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Năng lượng của cộng đồng là thứ kéo bạn dậy khi chuông báo thức reo.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Nâng đỡ đồng đội của bạn. Chiến thắng của họ cũng là chiến thắng của bạn.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Không ai trong chúng ta mạnh bằng tất cả chúng ta.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Cùng nhau, chúng ta biến 99 ngày thành nền móng của một cuộc sống mới.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Bạn không đơn độc trong hành trình này. Hãy nhìn sang trái, nhìn sang phải. Chúng ta ở đây cùng nhau.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Sức mạnh của đội nhóm nằm ở mỗi cá nhân. Sức mạnh của mỗi cá nhân nằm ở đội nhóm.' },
  { topic: 'Sức mạnh Cộng đồng & Đồng đội', text: 'Khi một người bước lên, cả đội sẽ cùng tiến lên.' },
];
